;;;
;;; Microsoft
;;;

; Microsoft Word 97-2003 Document
[doc]
ProgID = Document.1
MimeType = application/vnd.ms-word
TypeName = Word 97-2003 Document
FriendlyTypeNameResource = 1004
IconResource = 11

; Microsoft Word 97-2003 Template
[dot]
ProgID = Dot
MimeType = application/vnd.ms-word
TypeName = Word 97-2003 Template
FriendlyTypeNameResource = 1005
IconResource =

; Microsoft Word Document
[docx]
ProgID = Document.12
MimeType = application/vnd.openxmlformats-officedocument.wordprocessingml.document
TypeName = Office Open XML Document
FriendlyTypeNameResource = 1000
IconResource = 7
MenuText = 1000
ItemName = 1100

; Microsoft Word Template
[dotx]
ProgID = Dotx
MimeType = application/vnd.openxmlformats-officedocument.wordprocessingml.template
TypeName = Word Open XML Document Template
FriendlyTypeNameResource = 1006
IconResource = 30

; Microsoft Word Macro-Enabled Document
[docm]
ProgID = Docm
MimeType = application/vnd.ms-word.document.macroEnabled.12
TypeName = Word Macro-Enabled Document
FriendlyTypeNameResource = 1007
IconResource =

; Microsoft Word Macro-Enabled Template
[dotm]
ProgID = Dotm
MimeType = application/vnd.ms-word.template.macroEnabled.12
TypeName = Word Macro-Enabled Template
FriendlyTypeNameResource = 1008
IconResource =

; Microsoft Excel 97-2003 Workbook
[xls]
ProgID = Sheet.1
MimeType = application/vnd.ms-excel
TypeName = Excel 97-2003 Spreadsheet
FriendlyTypeNameResource = 1009
IconResource = 22

; Microsoft Excel 97-2003 Template
;[xlt]
;ProgID = Xlt
;MimeType = application/vnd.ms-excel
;TypeName = Microsoft Excel 97-2003 Template
;IconResource =

; Microsoft Excel Workbook
[xlsx]
ProgID = Sheet.12
MimeType = application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
TypeName = Office Open XML Spreadsheet
FriendlyTypeNameResource = 1001
IconResource = 10
MenuText = 1001
ItemName = 1101

; Microsoft Excel Template
[xltx]
ProgID = Xltx
MimeType = application/vnd.openxmlformats-officedocument.spreadsheetml.template
TypeName = Excel Template
FriendlyTypeNameResource = 1010
IconResource =

; Microsoft Excel Macro-Enabled Workbook
[xlsm]
ProgID = Xlsm
MimeType = application/vnd.ms-excel.sheet.macroEnabled.12
TypeName = Microsoft Excel Macro-Enabled Workbook
FriendlyTypeNameResource = 1011
IconResource = 37

; Microsoft Excel Macro-Enabled Template
[xltm]
ProgID = Xltm
MimeType = application/vnd.ms-excel.template.macroEnabled.12
TypeName = Excel Macro-Enabled Template
FriendlyTypeNameResource = 1012
IconResource =

; Microsoft Excel Binary Workbook
[xlsb]
ProgID = Xlsb
MimeType = application/vnd.ms-excel.sheet.binary.macroEnabled.12
TypeName = Excel Binary File Format
FriendlyTypeNameResource = 1013
IconResource = 32

; Microsoft PowerPoint 97-2003 Presentation
[ppt]
ProgID = Show.1
MimeType = application/vnd.ms-powerpoint
TypeName = PowerPoint 97-2003 Presentation
FriendlyTypeNameResource = 1014
IconResource = 1

; Microsoft PowerPoint 97-2003 Template
[pot]
ProgID = Pot
MimeType = application/vnd.ms-powerpoint
TypeName = PowerPoint Template
FriendlyTypeNameResource = 1015
IconResource = 26

; Microsoft PowerPoint 97-2003 Slideshow
[pps]
ProgID = SlideShow.1
MimeType = application/vnd.ms-powerpoint
TypeName = PowerPoint 97-2003 Slide Show
FriendlyTypeNameResource = 1016
IconResource = 2

; Microsoft PowerPoint Presentation
[pptx]
ProgID = Show.12
MimeType = application/vnd.openxmlformats-officedocument.presentationml.presentation
TypeName = Office Open XML Presentation
FriendlyTypeNameResource = 1002
IconResource = 9
MenuText = 1002
ItemName = 1102

; Microsoft PowerPoint Template
[potx]
ProgID = Potx
MimeType = application/vnd.openxmlformats-officedocument.presentationml.template
TypeName = PowerPoint Template
FriendlyTypeNameResource = 1017
IconResource =

; Microsoft PowerPoint Slideshow
[ppsx]
ProgID = SlideShow.12
MimeType = application/vnd.openxmlformats-officedocument.presentationml.slideshow
TypeName = Office Open XML Slide Show
FriendlyTypeNameResource = 1018
IconResource = 8

; Microsoft PowerPoint Macro-Enabled Presentation
[pptm]
ProgID = Pptm
MimeType = application/vnd.ms-powerpoint.presentation.macroEnabled.12
TypeName = PowerPoint Open XML Macro-Enabled Presentation
FriendlyTypeNameResource = 1019
IconResource = 27

; Microsoft PowerPoint Macro-Enabled Template
[potm]
ProgID = Potm
MimeType = application/vnd.ms-powerpoint.template.macroEnabled.12
TypeName = PowerPoint Macro-Enabled Template
FriendlyTypeNameResource = 1020
IconResource =

; Microsoft PowerPoint Macro-Enabled Slideshow
[ppsm]
ProgID = Ppsm
MimeType = application/vnd.ms-powerpoint.slideshow.macroEnabled.12
TypeName = PowerPoint Macro-Enabled Slideshow
FriendlyTypeNameResource = 1021
IconResource =

; Microsoft Visio 97-2003 Drawing
;[vsd]

; Microsoft Visio 97-2003 Template
;[vst]

; Microsoft Visio 97-2003 Stencil
;[vss]

; Microsoft Visio 97-2003 Drawing XML
;[vdx]

; Microsoft Visio 97-2003 Template XML
;[vtx]

; Microsoft Visio 97-2003 Stencil XML
;[vsx]

; Microsoft Visio Drawing
[vsdx]
ProgID = Vsdx
MimeType = application/vnd.ms-visio.drawing.main+xml
TypeName = Visio Drawing
FriendlyTypeNameResource = 1022
IconResource = 36

; Microsoft Visio Template
[vstx]
ProgID = Vstx
MimeType = application/vnd.ms-visio.template.main+xml
TypeName = Visio Template
FriendlyTypeNameResource = 1023
IconResource =

; Microsoft Visio Stencil
[vssx]
ProgID = Vssx
MimeType = application/vnd.ms-visio.stencil.main+xml
TypeName = Visio Stencil
FriendlyTypeNameResource = 1024
IconResource =

; Microsoft Visio Macro-Enabled Drawing
[vsdm]
ProgID = Vsdm
MimeType = application/vnd.ms-visio.drawing.macroEnabled.main+xml
TypeName = Visio Macro-Enabled Drawing
FriendlyTypeNameResource = 1025
IconResource =

; Microsoft Visio Macro-Enabled Template
[vstm]
ProgID = Vstm
MimeType = application/vnd.ms-visio.template.macroEnabled.main+xml
TypeName = Visio Macro-Enabled Template
FriendlyTypeNameResource = 1026
IconResource =

; Microsoft Visio Macro-Enabled Stencil
[vssm]
ProgID = Vssm
MimeType = application/vnd.ms-visio.stencil.macroEnabled.main+xml
TypeName = Visio Macro-Enabled Stencil
FriendlyTypeNameResource = 1027
IconResource =

; Microsoft XML Paper Specification
[xps]
ProgID = Xps
MimeType = application/vnd.ms-xpsdocument
TypeName = Open XML Paper Specification
FriendlyTypeNameResource = 1028
IconResource = 6

; Open XML Paper Specification
[oxps]
ProgID = Oxps
MimeType = application/oxps
TypeName = Open XML Paper Specification
FriendlyTypeNameResource = 1029
IconResource = 31

;;;
;;; OpenDocument
;;;

; OpenDocument Text
[odt]
ProgID = Document.2
MimeType = application/vnd.oasis.opendocument.text
TypeName = OpenDocument Text File
FriendlyTypeNameResource = 1030
IconResource = 18

; OpenDocument Text Template
[ott]
ProgID = Ott
MimeType = application/vnd.oasis.opendocument.text-template
TypeName = OpenDocument Text Template
FriendlyTypeNameResource = 1031
IconResource =

; OpenDocument Flat XML Text
[fodt]
ProgID = Fodt
MimeType = application/vnd.oasis.opendocument.text-flat-xml
TypeName = OpenDocument Flat XML Document
FriendlyTypeNameResource = 1032
IconResource = 35

; OpenDocument Spreadsheet
[ods]
ProgID = Sheet.2
MimeType = application/vnd.oasis.opendocument.spreadsheet
TypeName = OpenDocument Spreadsheet
FriendlyTypeNameResource = 1033
IconResource = 23

; OpenDocument Spreadsheet Template
[ots]
ProgID = Ots
MimeType = application/vnd.oasis.opendocument.spreadsheet-template
TypeName = OpenDocument Spreadsheet Template
FriendlyTypeNameResource = 1034
IconResource =

; OpenDocument Flat XML Spreadsheet
[fods]
ProgID = Fods
MimeType = application/vnd.oasis.opendocument.spreadsheet-flat-xml
TypeName = OpenDocument Flat XML Spreadsheet
FriendlyTypeNameResource = 1035
IconResource = 34

; OpenDocument Presentation
[odp]
ProgID = Show.2
MimeType = application/vnd.oasis.opendocument.presentation
TypeName = OpenDocument Presentation
FriendlyTypeNameResource = 1036
IconResource = 3

; OpenDocument Presentation Template
[otp]
ProgID = Otp
MimeType = application/vnd.oasis.opendocument.presentation-template
TypeName = OpenDocument Presentation Template
FriendlyTypeNameResource = 1037
IconResource =

; OpenDocument Flat XML Presentation
[fodp]
ProgID = Fodp
MimeType = application/vnd.oasis.opendocument.presentation-flat-xml
TypeName = OpenDocument Flat XML Presentation
FriendlyTypeNameResource = 1038
IconResource =

; OpenDocument Drawing
[odg]
ProgID = Odg
MimeType = application/vnd.oasis.opendocument.graphics
TypeName = OpenDocument Drawing
FriendlyTypeNameResource = 1039
IconResource =

; OpenDocument Drawing Template
;[otg]
;ProgID = Otg
;MimeType = application/vnd.oasis.opendocument.graphics-template
;TypeName = OpenDocument Drawing Template
;IconResource =

; OpenDocument Flat XML Drawing
;[fodg]
;ProgID = Fodg
;MimeType = application/vnd.oasis.opendocument.graphics-flat-xml
;TypeName = OpenDocument Flat XML Drawing
;IconResource =

;;;
;;; StarOffice
;;;

; StarOffice Writer Document
;[sxw]
;ProgID = Sxw
;MimeType = application/vnd.sun.xml.writer
;TypeName = StarOffice Writer Document
;IconResource =

; StarOffice Writer Document Template
;[stw]
;ProgID = Stw
;MimeType = application/vnd.sun.xml.writer.template
;TypeName = StarOffice Writer Document Template
;IconResource =

; StarOffice Calc Spreadsheet
;[sxc]
;ProgID = Sxc
;MimeType = application/vnd.sun.xml.calc
;TypeName = StarOffice Calc Spreadsheet
;IconResource =

; StarOffice Calc Spreadsheet Template
;[stc]
;ProgID = Stc
;MimeType = application/vnd.sun.xml.calc.template
;TypeName = StarOffice Calc Spreadsheet Template
;IconResource =

; StarOffice Impress Presentation
;[sxi]
;ProgID = Sxi
;MimeType = application/vnd.sun.xml.impress
;TypeName = StarOffice Impress Presentation
;IconResource =

; StarOffice Impress Presentation Template
;[sti]
;ProgID = Sti
;MimeType = application/vnd.sun.xml.impress.template
;TypeName = StarOffice Impress Presentation Template
;IconResource =

;;;
;;; Kingsoft
;;;

; Kingsoft Document
;[wps]
;ProgID = Wps
;MimeType = application/wps-office.wps
;TypeName = Kingsoft Document
;IconResource =

; Kingsoft Document Template
;[wpt]
;ProgID = Wpt
;MimeType = application/wps-office.wpt
;TypeName = Kingsoft Document Template
;IconResource =

; Kingsoft Spreadsheets
;[et]
;ProgID = Et
;MimeType = application/wps-office.et
;TypeName = Kingsoft Spreadsheets
;IconResource =

; Kingsoft Spreadsheets Template
;[ett]
;ProgID = Ett
;MimeType = application/wps-office.ett
;TypeName = Kingsoft Spreadsheets Template
;IconResource =

; Kingsoft Presentation
;[dps]
;ProgID = Dps
;MimeType = application/wps-office.dps
;TypeName = Kingsoft Presentation
;IconResource =

; Kingsoft Presentation Template
;[dpt]
;ProgID = Dpt
;MimeType = application/wps-office.dpt
;TypeName = Kingsoft Presentation Template
;IconResource =

;;;
;;; Apple
;;;

; Apple Pages Document
[pages]
ProgID = Pages
MimeType = application/vnd.apple.pages
TypeName = Apple Pages Document
FriendlyTypeNameResource = 1040
IconResource = 38

; Apple Numbers Spreadsheet
[numbers]
ProgID = Numbers
MimeType = application/vnd.apple.numbers
TypeName = Apple Numbers Spreadsheet
FriendlyTypeNameResource = 1041
IconResource = 39

; Apple Keynote Presentation
[key]
ProgID = Key
MimeType = application/vnd.apple.keynote
TypeName = Apple Keynote Presentation
FriendlyTypeNameResource = 1042
IconResource = 40

;;;
;;; Haansoft Hangul / Hancom Office
;;;

; Haansoft Hangul Document
;[hwp]
;ProgID = Hwp
;MimeType =
;TypeName = Haansoft Hangul Document
;IconResource =

; Haansoft Hangul Document Template
;[hwt]
;ProgID = Hwt
;MimeType =
;TypeName = Haansoft Hangul Document Template
;IconResource =

; HWPX Document
;[hwpx]
;ProgID = Hwpx
;MimeType =
;TypeName = HWPX Document
;IconResource =

; HWPML Document
;[hml]
;ProgID = Hml
;MimeType =
;TypeName = HWPML Document
;IconResource =

;;;
;;; Other
;;;

; DjVu Digital Document
[djvu]
ProgID = DjVu
MimeType = image/vnd.djvu
TypeName = Digital Document
FriendlyTypeNameResource = 1043
IconResource = 4

;[djv]
;MimeType = image/vnd.djvu

; FictionBook 2.0
[fb2]
ProgID = Fb2
MimeType = application/x-fictionbook+xml
TypeName = FictionBook 2.0 File
FriendlyTypeNameResource = 1044
IconResource = 29

; Portable Document Format
[pdf]
ProgID = Pdf
MimeType = application/pdf
TypeName = PDF
FriendlyTypeNameResource = 1003
IconResource = 5
MenuText = 1303
ItemName = 1103

; Rich Text Format
[rtf]
ProgID = Rtf
MimeType = application/rtf
TypeName = Rich Text Format File
FriendlyTypeNameResource = 1045
IconResource = 19

; Open eBook
[epub]
ProgID = Epub
MimeType = application/epub+zip
TypeName = Open eBook File
FriendlyTypeNameResource = 1046
IconResource = 28

; HyperText Markup Language
;[htm]
;MimeType = text/html

;[html]
;ProgID = Html
;MimeType = text/html
;TypeName = HyperText Markup Language
;IconResource = 21

; MIME HTML
;[mht]
;MimeType = application/x-mimearchive

;[mhtml]
;MimeType = application/x-mimearchive

; Extensible Markup Language
; Microsoft Word XML Document
; Microsoft Excel XML Spreadsheet
;[xml]
;ProgID = Xml
;MimeType = application/xml
;TypeName = Extensible Markup Language
;IconResource =

; Markdown document
[md]
ProgID = Md
MimeType = text/markdown
TypeName = Markdown Document
FriendlyTypeNameResource = 1047
IconResource =

; Plain Text
;[txt]
;ProgID = Txt
;MimeType = text/plain
;TypeName = Plain Text
;IconResource = 20

; Comma Separated Values
[csv]
ProgID = Csv
MimeType = text/csv
TypeName = Comma Separated Values
FriendlyTypeNameResource = 1048
IconResource = 24

; Tab Separated Values
[tsv]
ProgID = Tsv
MimeType = text/tab-separated-values
TypeName = Tab Separated Values
FriendlyTypeNameResource = 1049
IconResource =

; ONLYOFFICE Fillable Online Form
;[oform]
;ProgID = Oform
;MimeType =
;TypeName = ONLYOFFICE Fillable Online Form
;IconResource = 12

; ONLYOFFICE PDF Form
[docxf]
ProgID = Docxf
MimeType =
TypeName = ONLYOFFICE Form Template
FriendlyTypeNameResource = 1050
IconResource = 13
