const FILE_DOCUMENT = 0x0040;
const FILE_PRESENTATION = 0x0080;
const FILE_SPREADSHEET = 0x0100;
const FILE_CROSSPLATFORM = 0x0200;
const FILE_DRAW = 0x4000;

export const FileFormat = {
  FILE_UNKNOWN: 0x0000,

  FILE_DOCUMENT: FILE_DOCUMENT,
  FILE_DOCUMENT_DOCX: FILE_DOCUMENT + 0x0001,
  FILE_DOCUMENT_DOC: FILE_DOCUMENT + 0x0002,
  FILE_DOCUMENT_ODT: FILE_DOCUMENT + 0x0003,
  FILE_DOCUMENT_RTF: FILE_DOCUMENT + 0x0004,
  FILE_DOCUMENT_TXT: FILE_DOCUMENT + 0x0005,
  FILE_DOCUMENT_HTML: FILE_DOCUMENT + 0x0006,
  FILE_DOCUMENT_MHT: FILE_DOCUMENT + 0x0007,
  FILE_DOCUMENT_EPUB: FILE_DOCUMENT + 0x0008,
  FILE_DOCUMENT_FB2: FILE_DOCUMENT + 0x0009,
  FILE_DOCUMENT_MOBI: FILE_DOCUMENT + 0x000a,
  FILE_DOCUMENT_DOCM: FILE_DOCUMENT + 0x000b,
  FILE_DOCUMENT_DOTX: FILE_DOCUMENT + 0x000c,
  FILE_DOCUMENT_DOTM: FILE_DOCUMENT + 0x000d,
  FILE_DOCUMENT_ODT_FLAT: FILE_DOCUMENT + 0x000e,
  FILE_DOCUMENT_OTT: FILE_DOCUMENT + 0x000f,
  FILE_DOCUMENT_DOC_FLAT: FILE_DOCUMENT + 0x0010,
  FILE_DOCUMENT_OFORM: FILE_DOCUMENT + 0x0015,
  FILE_DOCUMENT_DOCXF: FILE_DOCUMENT + 0x0016,
  FILE_DOCUMENT_OFORM_PDF: FILE_DOCUMENT + 0x0017,
  FILE_DOCUMENT_PAGES: FILE_DOCUMENT + 0x0018,
  FILE_DOCUMENT_HWP: FILE_DOCUMENT + 0x0019,
  FILE_DOCUMENT_HWPX: FILE_DOCUMENT + 0x0020,
  FILE_DOCUMENT_XML: FILE_DOCUMENT + 0x0030,

  FILE_PRESENTATION: FILE_PRESENTATION,
  FILE_PRESENTATION_PPTX: FILE_PRESENTATION + 0x0001,
  FILE_PRESENTATION_PPT: FILE_PRESENTATION + 0x0002,
  FILE_PRESENTATION_ODP: FILE_PRESENTATION + 0x0003,
  FILE_PRESENTATION_PPSX: FILE_PRESENTATION + 0x0004,
  FILE_PRESENTATION_PPTM: FILE_PRESENTATION + 0x0005,
  FILE_PRESENTATION_PPSM: FILE_PRESENTATION + 0x0006,
  FILE_PRESENTATION_POTX: FILE_PRESENTATION + 0x0007,
  FILE_PRESENTATION_POTM: FILE_PRESENTATION + 0x0008,
  FILE_PRESENTATION_ODP_FLAT: FILE_PRESENTATION + 0x0009,
  FILE_PRESENTATION_OTP: FILE_PRESENTATION + 0x000a,
  FILE_PRESENTATION_ODG: FILE_PRESENTATION + 0x000c,
  FILE_PRESENTATION_KEY: FILE_PRESENTATION + 0x000d,

  FILE_SPREADSHEET: FILE_SPREADSHEET,
  FILE_SPREADSHEET_XLSX: FILE_SPREADSHEET + 0x0001,
  FILE_SPREADSHEET_XLS: FILE_SPREADSHEET + 0x0002,
  FILE_SPREADSHEET_ODS: FILE_SPREADSHEET + 0x0003,
  FILE_SPREADSHEET_CSV: FILE_SPREADSHEET + 0x0004,
  FILE_SPREADSHEET_XLSM: FILE_SPREADSHEET + 0x0005,
  FILE_SPREADSHEET_XLTX: FILE_SPREADSHEET + 0x0006,
  FILE_SPREADSHEET_XLTM: FILE_SPREADSHEET + 0x0007,
  FILE_SPREADSHEET_XLSB: FILE_SPREADSHEET + 0x0008,
  FILE_SPREADSHEET_ODS_FLAT: FILE_SPREADSHEET + 0x0009,
  FILE_SPREADSHEET_OTS: FILE_SPREADSHEET + 0x000a,
  FILE_SPREADSHEET_NUMBERS: FILE_SPREADSHEET + 0x000d,

  FILE_CROSSPLATFORM: FILE_CROSSPLATFORM,
  FILE_CROSSPLATFORM_PDF: FILE_CROSSPLATFORM + 0x0001,
  FILE_CROSSPLATFORM_SWF: FILE_CROSSPLATFORM + 0x0002,
  FILE_CROSSPLATFORM_DJVU: FILE_CROSSPLATFORM + 0x0003,
  FILE_CROSSPLATFORM_XPS: FILE_CROSSPLATFORM + 0x0004,
  FILE_CROSSPLATFORM_PDFA: FILE_CROSSPLATFORM + 0x0009,

  FILE_DRAW: FILE_DRAW,
  FILE_DRAW_VSDX: FILE_DRAW + 0x0001,
  FILE_DRAW_VSSX: FILE_DRAW + 0x0002,
  FILE_DRAW_VSTX: FILE_DRAW + 0x0003,
  FILE_DRAW_VSDM: FILE_DRAW + 0x0004,
  FILE_DRAW_VSSM: FILE_DRAW + 0x0005,
  FILE_DRAW_VSTM: FILE_DRAW + 0x0006,
};

const formatToString = Object.freeze({
  [FileFormat.FILE_DOCUMENT_DOC]: "doc",
  [FileFormat.FILE_DOCUMENT_DOCX]: "docx",
  [FileFormat.FILE_DOCUMENT_ODT]: "odt",
  [FileFormat.FILE_DOCUMENT_RTF]: "rtf",
  [FileFormat.FILE_DOCUMENT_TXT]: "txt",
  [FileFormat.FILE_DOCUMENT_HTML]: "html",
  [FileFormat.FILE_DOCUMENT_MHT]: "mht",
  [FileFormat.FILE_DOCUMENT_EPUB]: "epub",
  [FileFormat.FILE_DOCUMENT_FB2]: "fb2",
  [FileFormat.FILE_DOCUMENT_DOCM]: "docm",
  [FileFormat.FILE_DOCUMENT_DOTX]: "dotx",
  [FileFormat.FILE_DOCUMENT_OTT]: "ott",
  [FileFormat.FILE_DOCUMENT_OFORM]: "oform",
  [FileFormat.FILE_DOCUMENT_DOCXF]: "docxf",
  [FileFormat.FILE_DOCUMENT_OFORM_PDF]: "pdf",
  [FileFormat.FILE_DOCUMENT_ODT_FLAT]: "fodt",
  [FileFormat.FILE_DOCUMENT_DOTM]: "dotm",
  [FileFormat.FILE_DOCUMENT_XML]: "xml",
  [FileFormat.FILE_DOCUMENT_PAGES]: "pages",
  [FileFormat.FILE_DOCUMENT_HWP]: "hwp",
  [FileFormat.FILE_DOCUMENT_HWPX]: "hwpx",

  [FileFormat.FILE_SPREADSHEET_XLS]: "xls",
  [FileFormat.FILE_SPREADSHEET_XLTX]: "xltx",
  [FileFormat.FILE_SPREADSHEET_XLSX]: "xlsx",
  [FileFormat.FILE_SPREADSHEET_XLSB]: "xlsb",
  [FileFormat.FILE_SPREADSHEET_ODS]: "ods",
  [FileFormat.FILE_SPREADSHEET_CSV]: "csv",
  [FileFormat.FILE_SPREADSHEET_OTS]: "ots",
  [FileFormat.FILE_SPREADSHEET_XLTM]: "xltm",
  [FileFormat.FILE_SPREADSHEET_XLSM]: "xlsm",
  [FileFormat.FILE_SPREADSHEET_ODS_FLAT]: "fods",
  [FileFormat.FILE_SPREADSHEET_NUMBERS]: "numbers",

  [FileFormat.FILE_PRESENTATION_PPT]: "ppt",
  [FileFormat.FILE_PRESENTATION_POTX]: "potx",
  [FileFormat.FILE_PRESENTATION_PPTX]: "pptx",
  [FileFormat.FILE_PRESENTATION_ODP]: "odp",
  [FileFormat.FILE_PRESENTATION_PPSX]: "ppsx",
  [FileFormat.FILE_PRESENTATION_OTP]: "otp",
  [FileFormat.FILE_PRESENTATION_PPTM]: "pptm",
  [FileFormat.FILE_PRESENTATION_PPSM]: "ppsm",
  [FileFormat.FILE_PRESENTATION_POTM]: "potm",
  [FileFormat.FILE_PRESENTATION_ODP_FLAT]: "fodp",
  [FileFormat.FILE_PRESENTATION_KEY]: "key",
  [FileFormat.FILE_PRESENTATION_ODG]: "odg",

  [FileFormat.FILE_CROSSPLATFORM_PDFA]: "pdf",
  [FileFormat.FILE_CROSSPLATFORM_PDF]: "pdf",
  [FileFormat.FILE_CROSSPLATFORM_DJVU]: "djvu",
  [FileFormat.FILE_CROSSPLATFORM_XPS]: "xps",

  [FileFormat.FILE_DRAW_VSTX]: "vsdx",
  [FileFormat.FILE_DRAW_VSSX]: "vsdx",
  [FileFormat.FILE_DRAW_VSDM]: "vsdx",
  [FileFormat.FILE_DRAW_VSSM]: "vsdx",
  [FileFormat.FILE_DRAW_VSTM]: "vsdx",
  [FileFormat.FILE_DRAW_VSDX]: "vsdx",
});

const extensionToFormat = Object.freeze({
  doc: FileFormat.FILE_DOCUMENT_DOC,
  docx: FileFormat.FILE_DOCUMENT_DOCX,
  odt: FileFormat.FILE_DOCUMENT_ODT,
  rtf: FileFormat.FILE_DOCUMENT_RTF,
  txt: FileFormat.FILE_DOCUMENT_TXT,
  html: FileFormat.FILE_DOCUMENT_HTML,
  mht: FileFormat.FILE_DOCUMENT_MHT,
  epub: FileFormat.FILE_DOCUMENT_EPUB,
  fb2: FileFormat.FILE_DOCUMENT_FB2,
  docm: FileFormat.FILE_DOCUMENT_DOCM,
  dotx: FileFormat.FILE_DOCUMENT_DOTX,
  ott: FileFormat.FILE_DOCUMENT_OTT,
  oform: FileFormat.FILE_DOCUMENT_OFORM,
  docxf: FileFormat.FILE_DOCUMENT_DOCXF,
  pdf: FileFormat.FILE_DOCUMENT_OFORM_PDF,
  fodt: FileFormat.FILE_DOCUMENT_ODT_FLAT,
  dotm: FileFormat.FILE_DOCUMENT_DOTM,
  xml: FileFormat.FILE_DOCUMENT_XML,
  pages: FileFormat.FILE_DOCUMENT_PAGES,
  hwp: FileFormat.FILE_DOCUMENT_HWP,
  hwpx: FileFormat.FILE_DOCUMENT_HWPX,

  xls: FileFormat.FILE_SPREADSHEET_XLS,
  xltx: FileFormat.FILE_SPREADSHEET_XLTX,
  xlsx: FileFormat.FILE_SPREADSHEET_XLSX,
  xlsb: FileFormat.FILE_SPREADSHEET_XLSB,
  ods: FileFormat.FILE_SPREADSHEET_ODS,
  csv: FileFormat.FILE_SPREADSHEET_CSV,
  ots: FileFormat.FILE_SPREADSHEET_OTS,
  xltm: FileFormat.FILE_SPREADSHEET_XLTM,
  xlsm: FileFormat.FILE_SPREADSHEET_XLSM,
  fods: FileFormat.FILE_SPREADSHEET_ODS_FLAT,
  numbers: FileFormat.FILE_SPREADSHEET_NUMBERS,

  ppt: FileFormat.FILE_PRESENTATION_PPT,
  potx: FileFormat.FILE_PRESENTATION_POTX,
  pptx: FileFormat.FILE_PRESENTATION_PPTX,
  odp: FileFormat.FILE_PRESENTATION_ODP,
  ppsx: FileFormat.FILE_PRESENTATION_PPSX,
  otp: FileFormat.FILE_PRESENTATION_OTP,
  pptm: FileFormat.FILE_PRESENTATION_PPTM,
  ppsm: FileFormat.FILE_PRESENTATION_PPSM,
  potm: FileFormat.FILE_PRESENTATION_POTM,
  fodp: FileFormat.FILE_PRESENTATION_ODP_FLAT,
  key: FileFormat.FILE_PRESENTATION_KEY,
  odg: FileFormat.FILE_PRESENTATION_ODG,

  djvu: FileFormat.FILE_CROSSPLATFORM_DJVU,
  xps: FileFormat.FILE_CROSSPLATFORM_XPS,
});

export function formatToEditor(f) {
  if (f > FILE_PRESENTATION && f < FILE_SPREADSHEET) return "slide";
  else if (f > FILE_SPREADSHEET && f < FILE_CROSSPLATFORM) return "cell";
  else if (f > FILE_CROSSPLATFORM || f === FileFormat.FILE_DOCUMENT_OFORM_PDF) return "pdf";
  else return "word";
}

export function parseFileFormat(format) {
  return formatToString[format] || "neutral";
}

export function fileExtensionToFileFormat(extension) {
  const key = extension[0] === "." ? extension.substring(1) : extension;
  return extensionToFormat[key] || FileFormat.FILE_UNKNOWN;
}
